Name=DEFAULT
Level=0
Difficulty=1
Money=0
LevelAim=10
MaxMana=500
Deaths=0
Kills=0
Actor=heal
	Health=900
	Mana=50
Unlocks=
	First_hit=true
	Warm_up=true
	Anger=true
	Strength=true
	Bloodlust=false
	Blood_thirstiness=false
	Precision=false
	Range=false
	Blood_pact=false
	Blood_armor=false