Name=DEFAULT
Level=1
Difficulty=1
Money=0
LevelAim=10
MaxMana=200
Deaths=0
Kills=0
Actor=heal_playable
	Health=900
	Mana=50
Unlocks=
	First_hit=false
	Warm_up=false
	Anger=false
	Strength=false
	Bloodlust=false
	Blood_thirstiness=false
	Precision=false
	Range=false
	Blood_pact=false
	Blood_armor=false