name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest
    environment: Wiki Access
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Documentation Writer
      run: dotnet build --no-restore
    - name: Generate documentation
      run: |
        dotnet DocWriter.dll -skip-header
        mkdir results
        mv Documentation.html results/Documentation.md
    - name: Upload documentation
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: results
        ACTION_MAIL: documentation@users.noreply.github.com
        ACTION_NAME: documentation
        OWNER: abc013
        REPO_NAME: WarriorsSnuggery
        WIKI_PUSH_MESSAGE: Update documentation to latest changes