name: .NET Test Build

on: [push]

jobs:
  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  Publish:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish (windows_x64)
      run: dotnet publish /p:PublishProfile=windows_x64
    - name: Archive published binaries (windows_x64)
      uses: actions/upload-artifact@v2
      with:
        name: publish_win_x64
        path: publish_win_x64
    - name: Publish (linux_x64)
      run: dotnet publish /p:PublishProfile=linux_x64
    - name: Archive published binaries (linux_x64)
      uses: actions/upload-artifact@v2
      with:
        name: publish_linux_x64
        path: publish_linux_x64
    - name: Publish (osx_x64)
      run: dotnet publish /p:PublishProfile=osx_x64
    - name: Archive published binaries (osx_x64)
      uses: actions/upload-artifact@v2
      with:
        name: publish_osx_x64
        path: publish_osx_x64
